### ISSUE TITLE
[BUG]如果出现了下载链接则会下载文件，导致严重卡顿

### ISSUE THREAD

**Issue by CreeperAWA** [Eticeweng/LiteLoaderQQNT-Link-Preview#1]
如果聊天记录出现了一个下载链接，则插件会一直下载，耗费大量流量且导致严重卡顿，希望可以加入判断，不下载文件链接，只显示文件名
以下是日志
`[!Renderer:Log:2] [link-preview] :target matched
[19772:0623/175457.347:INFO:CONSOLE(0)] "[link-preview] :target matched", source: local:///D:\%E6%96%87%E6%A1%A3\LiteloaderQQNT\plugins\LLAPI\src\./renderer/utils.js (0)
:reading 0
:reading 15547
:reading 31869
:reading 48253
:reading 64637
:reading 81021
:reading 97405
:reading 113789
...`
因[链接](https://public-cdn.cloud.unitychina.cn/hub/prod/UnityHubSetup.exe)（UnityHub）指向的文件巨大，产生了很多reading，已打...省略

**Comment by Eticeweng** [comment]
最新版本应该修复了这个问题才对，或许可以确定你在使用的是否最新版本？
至于提到的文件名显示功能暂时没有头绪怎么去实现，请谅解
![image](https://github.com/Eticeweng/LiteLoaderQQNT-Link-Preview/assets/43090280/e80a99a7-0b4c-4ed2-a905-43c0826d71ca)

**Comment by leoguan88** [comment]
请问如何查看日志啊？

**Comment by Eticeweng** [comment]
> 请问如何查看日志啊？

请参考liteloader的[官方文档](https://liteloaderqqnt.github.io/docs/introduction.html#%E8%B0%83%E8%AF%95%E4%BB%A3%E7%A0%81)
